/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.pashabank.posemu;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rsamadov
 */
import java.awt.Window;

public class ChooseCard extends javax.swing.JDialog {

    /**
     * Creates new form ChooseCard
     */
    private Database db;
    private final DefaultTableModel tCardsModel;

    public ChooseCard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.db = Database.getInstance();
        this.tCardsModel = (DefaultTableModel) this.TaChooseCard.getModel();
        loadInitData();
    }

    private void loadInitData() {
        try {
            List<Card> cards = db.getCards();
            for (Card card : cards) {
                Object[] row = cardToRow(card);
                this.tCardsModel.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Exception: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Object[] cardToRow(Card card) {
        Object[] row = new Object[5];
        row[0] = card.getCard();
        row[1] = card.getKeySetid();
        row[2] = card.getTrack1();
        row[3] = card.getTrack2();
        row[4] = card.getDescription();
        return row;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TaChooseCard = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bChoose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TaChooseCard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Card", "KeySetID", "Track1", "Track2", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TaChooseCard);

        jLabel1.setText("                           Please Choose Card");

        bChoose.setText("Choose");
        bChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(bChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bChoose)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Card getSelectedInterface(int selectedRow) {
        return new Card(
                TaChooseCard.getModel().getValueAt(TaChooseCard.getSelectedRow(), 0).toString(),
                Integer.valueOf(TaChooseCard.getModel().getValueAt(TaChooseCard.getSelectedRow(), 1).toString()),
                TaChooseCard.getModel().getValueAt(TaChooseCard.getSelectedRow(), 2).toString(),
                TaChooseCard.getModel().getValueAt(TaChooseCard.getSelectedRow(), 3).toString(),
                TaChooseCard.getModel().getValueAt(TaChooseCard.getSelectedRow(), 4).toString()
        );
    }

    private void bChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChooseActionPerformed

        int selectedRow = this.TaChooseCard.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        System.out.println(getSelectedInterface(selectedRow).toString());
        this.dispose();
    }//GEN-LAST:event_bChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TaChooseCard;
    private javax.swing.JButton bChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
