/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.pashabank.posemu;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rsamadov
 */
public class DialogReceipt extends javax.swing.JDialog {

    /**
     * Creates new form DialogReceipt
     */
    
    private Database db;

    public DialogReceipt(java.awt.Frame parent, boolean modal, String trn) {
        super(parent, modal);
        initComponents();
        String screenData = "\n\n\n\n\n\n\n\n\n\n\n\n    Receipt of transaction   ";
        this.db = Database.getInstance();
        try {
            Receipt rcp = db.getReceipt(trn);
            screenData=screenData + "\n" + rcp.getAmount() + "\n"  + rcp.getCard() + "\n"  + rcp.getDate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error occured while closing databaseL " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }        
        tajReceipt.setText(screenData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tajReceipt = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tajReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tajReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea tajReceipt;
    // End of variables declaration//GEN-END:variables
}
